#!/usr/bin/env bash
set -uo pipefail
REAL="${OPENCODE_BIN:-$HOME/.opencode/bin/opencode}"
MAX_ATTEMPTS="${OPENCODE_MAX_ATTEMPTS:-6}"
RETRY_DELAY="${OPENCODE_RETRY_DELAY_SECONDS:-30}"
MODEL_SWITCH_DELAY="${OPENCODE_MODEL_SWITCH_DELAY_SECONDS:-5}"
NETWORK_STALL_SECONDS="${OPENCODE_NETWORK_STALL_SECONDS:-300}"
LOG="$(mktemp)"; STALL_FLAG="$(mktemp)"
CONTROL_ACTIVE=false; CHILD_PID=""; MONITOR_PID=""; START_HEAD=""; REPAIR_INTENT=false
NETWORK_RE='(network_error|NetworkError|network error|fetch failed|APIConnectionError|ECONNRESET|ECONNREFUSED|EAI_AGAIN|ENETUNREACH|ENOTFOUND|ETIMEDOUT|timed out|timeout|socket hang up|connection (reset|refused|closed|error)|upstream.*(reset|closed|unavailable|error)|HTTP[^0-9]*(429|500|502|503|504)|status[^0-9]*(429|500|502|503|504)|too many requests|rate.?limit|service unavailable|bad gateway|gateway timeout|temporar(y|ily) unavailable|TLS|SSL.*error|Unexpected server error|internal server error|FreeUsageLimitError|provider error|model.*(unavailable|not found)|forbidden|HTTP[^0-9]*403)'
CONTROL_PATHS=("AGENTS.md" ".opencode/agents" "docs/agents" "docs/roles" "SPIDER_MASTER_PROMPT.md" "SPIDER_ARCHITECTURE_V2.md" "SPIDER_ARCHITECTURE_V3.md" "directives/CAPABILITY_CAPSULE.md" "directives/AUDITOR.md" "directives/LANE_DIRECTOR.md" "directives/LAB_DIRECTOR.md" "directives/INTEL_REPRO.md" "directives/INTEL_AUDITOR.md" "directives/INTEL_DIRECTOR.md" "directives/PRODUCT_DIRECTOR.md" "directives/PRODUCT_OPTIMIZATION.md" "directives/NONTERMINAL_AUTONOMY.md" "intel/competitor_seed.json")
restore_path_from_head(){ local p="$1"; git reset -q HEAD -- "$p" 2>/dev/null || true; if git cat-file -e "HEAD:$p" 2>/dev/null; then git checkout -q -- "$p" 2>/dev/null || true; else rm -rf -- "$p"; fi; git clean -fdq -- "$p" 2>/dev/null || true; }
restore_control_plane(){ [[ "$CONTROL_ACTIVE" == true ]] || return 0; local p residue=""; for p in "${CONTROL_PATHS[@]}"; do restore_path_from_head "$p"; done; CONTROL_ACTIVE=false; for p in "${CONTROL_PATHS[@]}"; do [[ -z "$(git status --porcelain -- "$p" 2>/dev/null || true)" ]] || residue+="$p "; done; [[ -z "$residue" ]] || { echo "::error::Control-plane restoration left residue in: $residue" >&2; return 1; }; }
cleanup(){ [[ -z "$MONITOR_PID" ]] || kill "$MONITOR_PID" 2>/dev/null || true; [[ -z "$CHILD_PID" ]] || kill "$CHILD_PID" 2>/dev/null || true; restore_control_plane || true; rm -f "$LOG" "$STALL_FLAG"; }
trap cleanup EXIT INT TERM
stage_control_plane(){ local source_ref="origin/main" p; if ! git fetch -q origin main; then echo "::warning::Unable to refresh origin/main control plane; using workflow checkout definitions."; source_ref="${GITHUB_SHA:-HEAD}"; fi; for p in "${CONTROL_PATHS[@]}"; do git cat-file -e "$source_ref:$p" 2>/dev/null && git checkout -q "$source_ref" -- "$p" || true; done; CONTROL_ACTIVE=true; rm -rf /tmp/spider_control; mkdir -p /tmp/spider_control; for p in "${CONTROL_PATHS[@]}"; do if [[ -e "$p" ]]; then mkdir -p "/tmp/spider_control/$(dirname "$p")"; cp -a "$p" "/tmp/spider_control/$p"; fi; done; mkdir -p /tmp/spider_control/state; git cat-file -e "$source_ref:state/opencode_model_router.json" 2>/dev/null && git show "$source_ref:state/opencode_model_router.json" > /tmp/spider_control/state/opencode_model_router.json || true; }
validate_agent_card(){ local requested="" prev="" arg registry="docs/agents/AGENT_CARDS.md"; [[ -f "$registry" ]] || { echo "::error::Missing canonical SPIDER agent registry" >&2; return 64; }; local bad=0 file id count; while IFS= read -r file; do id="${file#.opencode/agents/}"; id="${id%.md}"; count=$(grep -Fc "<!-- AGENT_CARD: ${id} " "$registry" || true); [[ "$count" -eq 1 ]] || { echo "::error::Agent '$id' has $count canonical cards" >&2; bad=1; }; done < <(find .opencode/agents -type f -name '*.md' | sort); while IFS= read -r id; do [[ -z "$id" || -f ".opencode/agents/${id}.md" ]] || { echo "::error::Canonical card '$id' has no agent definition" >&2; bad=1; }; done < <(grep '^<!-- AGENT_CARD:' "$registry" | awk '{print $3}'); [[ "$bad" -eq 0 ]] || return 66; for arg in "$@"; do if [[ "$prev" == "--agent" ]]; then requested="$arg"; break; fi; case "$arg" in --agent=*) requested="${arg#--agent=}"; break;; esac; prev="$arg"; done; [[ -n "$requested" ]] || return 0; local marker; marker=$(grep -F "<!-- AGENT_CARD: ${requested} " "$registry" | head -n1 || true); [[ -n "$marker" ]] || { echo "::error::Agent '$requested' has no canonical operating card" >&2; return 64; }; [[ "$marker" != *"status=LEGACY_DISABLED"* || "${SPIDER_ALLOW_LEGACY_AGENT:-0}" == "1" ]] || return 65; echo "SPIDER_AGENT_CARD_OK agent=${requested}"; }
agent_from_args(){ local prev="" a; for a in "$@"; do if [[ "$prev" == "--agent" ]]; then echo "$a"; return; fi; case "$a" in --agent=*) echo "${a#--agent=}"; return;; esac; prev="$a"; done; }
role_for_agent(){ case "$1" in graph_runner|physics_runner|frontier_research_lead|dynamics_physicist|graph_state_architect|graph_capability_compiler) echo science;; independent_auditor|frontier_research_auditor|intel_auditor|runtime_auditor) echo science_audit;; intel_runner|ecosystem_scout) echo scout;; intel_reproducer|runtime_runner|product_engineer|beta_builder) echo coding;; product_work_auditor|beta_tester_auditor|graph_efficiency_redteam) echo coding_audit;; beta_architect) echo architect;; evidence_curator) echo curator;; lane_director|runtime_director|intel_research_director|frontier_research_director|product_director|chief_cto|cto_*) echo director;; *) echo general;; esac; }
router_file="/tmp/spider_control/state/opencode_model_router.json"
load_model_candidates(){ local role="$1" requested="$2" m authoritative=false; local -a list=(); if [[ "${SPIDER_DISABLE_MODEL_ROUTER:-0}" != "1" && -s "$router_file" ]]; then authoritative=true; while IFS= read -r m; do [[ -n "$m" && "$m" != null ]] && list+=("opencode/$m"); done < <(jq -r --arg r "$role" '.fallbacks[$r][]? // empty' "$router_file" 2>/dev/null || true); if (( ${#list[@]} == 0 )); then m=$(jq -r --arg r "$role" '.selected[$r] // .selected.general // empty' "$router_file" 2>/dev/null || true); [[ -n "$m" && "$m" != null ]] && list+=("opencode/$m"); fi; fi; if [[ "$authoritative" == false ]]; then [[ ${#list[@]} -gt 0 || -z "$requested" ]] || list+=("$requested"); (( ${#list[@]} > 0 )) || list+=("opencode/mimo-v2.5-free" "opencode/hy3-free" "opencode/muse-spark-1.2-contributor-free"); fi; printf '%s\n' "${list[@]}" | awk 'NF && !seen[$0]++'; }
replace_model_arg(){ local new="$1"; shift; local -a src=("$@") dst=(); local i=0 replaced=false; while (( i < ${#src[@]} )); do case "${src[$i]}" in --model) dst+=("--model" "$new"); i=$((i+2)); replaced=true;; --model=*) dst+=("--model=$new"); i=$((i+1)); replaced=true;; *) dst+=("${src[$i]}"); i=$((i+1));; esac; done; if [[ "$replaced" == false ]]; then if (( ${#dst[@]} > 0 )) && [[ "${dst[0]}" == run ]]; then dst=("run" "--model" "$new" "${dst[@]:1}"); else dst+=("--model" "$new"); fi; fi; printf '%s\0' "${dst[@]}"; }
for arg in "$@"; do [[ "$arg" == REPAIR\ * || "$arg" == *" REPAIR "* ]] && { REPAIR_INTENT=true; break; }; done; [[ "${SPIDER_REQUIRE_DELTA:-0}" == "1" ]] && REPAIR_INTENT=true
stage_control_plane; START_HEAD=$(git rev-parse HEAD 2>/dev/null || echo ""); validate_agent_card "$@"; rc=$?; [[ "$rc" -eq 0 ]] || { restore_control_plane || true; exit "$rc"; }
AGENT=$(agent_from_args "$@"); ROLE="${SPIDER_MODEL_ROLE:-$(role_for_agent "$AGENT")}"; REQUESTED_MODEL=""; prev=""; for arg in "$@"; do if [[ "$prev" == "--model" ]]; then REQUESTED_MODEL="$arg"; break; fi; case "$arg" in --model=*) REQUESTED_MODEL="${arg#--model=}"; break;; esac; prev="$arg"; done; mapfile -t MODEL_CANDIDATES < <(load_model_candidates "$ROLE" "$REQUESTED_MODEL"); (( ${#MODEL_CANDIDATES[@]} > 0 )) || { echo "::error::No healthy OpenCode model candidate for role=$ROLE" >&2; restore_control_plane || true; exit 75; }; echo "SPIDER_MODEL_ROUTER role=$ROLE agent=${AGENT:-builtin} candidates=$(IFS=,; echo "${MODEL_CANDIDATES[*]}")"
run_once(){ local model="$1"; shift; : > "$LOG"; rm -f "$STALL_FLAG"; local workdir="${GITHUB_WORKSPACE:-$PWD}"; local -a routed=(); while IFS= read -r -d '' a; do routed+=("$a"); done < <(replace_model_arg "$model" "$@"); ( cd "$workdir" || exit 70; "$REAL" "${routed[@]}" ) > >(tee -a "$LOG") 2> >(tee -a "$LOG" >&2) & CHILD_PID=$!; ( local last_size=0 last_change now size; last_change=$(date +%s); while kill -0 "$CHILD_PID" 2>/dev/null; do sleep 15; size=$(wc -c < "$LOG" 2>/dev/null || echo 0); now=$(date +%s); if [[ "$size" -ne "$last_size" ]]; then last_size="$size"; last_change="$now"; elif (( now-last_change >= NETWORK_STALL_SECONDS )); then if grep -Eiq "$NETWORK_RE" "$LOG"; then echo "SPIDER_MODEL_NETWORK_STALL model=$model" | tee -a "$LOG" >&2; touch "$STALL_FLAG"; kill "$CHILD_PID" 2>/dev/null || true; sleep 5; kill -9 "$CHILD_PID" 2>/dev/null || true; exit 0; fi; last_change="$now"; fi; done ) & MONITOR_PID=$!; wait "$CHILD_PID"; local child_rc=$?; kill "$MONITOR_PID" 2>/dev/null || true; wait "$MONITOR_PID" 2>/dev/null || true; CHILD_PID=""; MONITOR_PID=""; [[ -f "$STALL_FLAG" ]] && return 75; return "$child_rc"; }
attempt=1; model_index=0
while (( attempt <= MAX_ATTEMPTS )); do model="${MODEL_CANDIDATES[$model_index]}"; echo "SPIDER_OPENCODE_ATTEMPT=$attempt/$MAX_ATTEMPTS model=$model role=$ROLE"; run_once "$model" "$@"; rc=$?; if [[ "$rc" -eq 0 ]]; then restore_control_plane || exit 1; if [[ "$REPAIR_INTENT" == true ]]; then CURRENT_HEAD=$(git rev-parse HEAD 2>/dev/null || echo ""); WORKTREE_DELTA=$(git status --porcelain 2>/dev/null || true); [[ "$CURRENT_HEAD" != "$START_HEAD" || -n "$WORKTREE_DELTA" ]] || { echo "::error::SPIDER_ZERO_DELTA_REPAIR" >&2; exit 67; }; fi; echo "SPIDER_MODEL_SUCCESS role=$ROLE model=$model"; exit 0; fi; if [[ "$rc" -eq 75 ]] || grep -Eiq "$NETWORK_RE" "$LOG"; then if (( model_index + 1 < ${#MODEL_CANDIDATES[@]} )); then model_index=$((model_index+1)); attempt=$((attempt+1)); echo "::warning::Free model operational failure; rotating to ${MODEL_CANDIDATES[$model_index]}"; sleep "$MODEL_SWITCH_DELAY"; continue; fi; if (( attempt < MAX_ATTEMPTS )); then model_index=0; attempt=$((attempt+1)); echo "::warning::Routed pool exhausted once; retrying after ${RETRY_DELAY}s"; sleep "$RETRY_DELAY"; continue; fi; echo "SPIDER_TRANSIENT_MODEL_POOL_EXHAUSTED attempts=$MAX_ATTEMPTS role=$ROLE" >&2; restore_control_plane || true; exit 75; fi; echo "OpenCode failed without provider/network signature; preserving substantive/control failure (rc=$rc model=$model)" >&2; restore_control_plane || true; exit "$rc"; done
restore_control_plane || true; exit 75
