worker_processes 1;
error_log /tmp/spider-runtime/nginx_error.log;
pid /tmp/spider-runtime/nginx.pid;
events {
    worker_connections 256;
}
http {
    access_log off;
    upstream distributed_sticky {
        hash $request_uri consistent;
        server 127.0.0.1:18981;
        server 127.0.0.1:18982;
        server 127.0.0.1:18983;
        server 127.0.0.1:18984;
    }
    server {
        listen 18980;
        location / {
            proxy_pass http://distributed_sticky;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Worker-Pid $upstream_addr;
        }
    }
}
